# Generated by Django 4.2.6 on 2024-06-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_branch_userprofile_college_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='CodeForces_profile',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's Codeforces profile.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Codechef_profile',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's CodeChef profile.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Github_profile',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's Github profile.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Linkedin_profile',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's Linkedin_profile.", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leetcode_profile',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's Leetcode profile.", max_length=1000, null=True),
        ),
    ]
