# Generated by Django 4.2.6 on 2024-06-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_codeforces_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aboutme',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
