# Generated by Django 4.2.6 on 2024-06-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_aboutme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cloud',
            field=models.TextField(blank=True, help_text='Optional. List of cloud technologies known by the user.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='coding_languages',
            field=models.TextField(blank=True, help_text='Optional. List of coding languages known by the user.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='databases',
            field=models.TextField(blank=True, help_text='Optional. List of databases known by the user.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dev_framework',
            field=models.TextField(blank=True, help_text='Optional. List of development frameworks known by the user.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='other',
            field=models.TextField(blank=True, help_text='Optional. List of Other technologies known by the user.'),
        ),
    ]
