# Generated by Django 4.2.6 on 2024-06-18 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_cloud_userprofile_coding_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProjects',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('projectName', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=100, null=True)),
                ('projectLink', models.URLField(blank=True, help_text="Optional. URL of the user's Leetcode profile.", max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
