# Generated by Django 4.2.6 on 2024-06-18 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprojects',
            name='GithubLink',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's project code link.", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='projectLink',
            field=models.URLField(blank=True, help_text="Optional. URL of the user's project host link.", max_length=1000, null=True),
        ),
    ]
