# Generated by Django 4.2.6 on 2024-06-18 02:05

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprojects_githublink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.user_profilephoto_file_path),
        ),
    ]
