# Generated by Django 4.2.6 on 2024-06-18 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_profile_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProjects',
        ),
    ]
