# Generated by Django 4.2.6 on 2024-06-18 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_userprojects_techstack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='id',
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='duration_weeks',
            field=models.IntegerField(blank=True, help_text='Estimated duration in weeks', null=True),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='openRequest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20),
        ),
        migrations.AddField(
            model_name='userprojects',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='description',
            field=models.TextField(default=1200, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprojects',
            name='projectName',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectCollaborator',
            fields=[
                ('Col_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('developer', 'Developer'), ('designer', 'Designer'), ('project_manager', 'Project Manager'), ('other', 'Other')], default='developer', max_length=20)),
                ('skills', models.TextField(blank=True, help_text='Skills relevant to the project')),
                ('responsibilities', models.TextField(blank=True, help_text='Responsibilities in the project')),
                ('collaboration_status', models.CharField(blank=True, max_length=20, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.userprojects')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, help_text='Optional. Message accompanying the request.', max_length=300, null=True)),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date requested')),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_declined', models.BooleanField(default=False)),
                ('is_pending', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='projects.userprojects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
